# Build settings

baseurl: ""
port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Eetu Netti"
description: "Game Projects from Strategic Board Games to Tactical RPGs"
author:      "Eetu Netti"
